# -*- encoding: utf-8 -*-

=begin
#Bitbucket API

#Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

The version of the OpenAPI document: 2.0
Contact: support@bitbucket.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "bitbucket/version"

Gem::Specification.new do |s|
  s.name        = "bitbucket"
  s.version     = Bitbucket::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Persona Identities"]
  s.email       = ["support@bitbucket.org"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Bitbucket API Ruby Gem"
  s.description = "Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
